name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    env:
      SCHEME: ReactorKit
      CODECOV_PACKAGE_NAME: ReactorKit
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 13 Pro,OS=latest

          - sdk: macosx
            destination: arch=x86_64

          - sdk: appletvsimulator
            destination: platform=tvOS Simulator,name=Apple TV,OS=latest

    steps:
      - uses: actions/checkout@v2

      - name: List SDKs and Devices
        run: xcodebuild -showsdks; xcrun xctrace list devices

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild clean build test \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            -configuration Debug \
            -enableCodeCoverage YES \
            -resultBundlePath "./${{ matrix.env.sdk }}.xcresult" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
        env:
          SDK: ${{ matrix.env.sdk }}
          DESTINATION: ${{ matrix.env.destination }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          xcode: true
          xcode_archive_path: "./${{ matrix.env.sdk }}.xcresult"
